### ISSUE TITLE
Implement Ping-Check before connecting to an AuthNode

### ISSUE THREAD

**Issue by fabianriewe** [ArVerify/arverify-js#1]
We should implement a ping-request to the AuthNode before doing any interaction with it. Otherwise it could happen, that we interact with an offline AuthNode

**Comment by johnletey** [comment]
@fabianriewe Ah yes, thanks for spotting this 🙌🏻

This has been resolved in https://github.com/ArVerify/arverify-js/commit/b35fc8090131613cfa9d1e0cb679e446c374c6ff and `v2.0.1` has been released.
